name: Other
description: Use this for any other issues. Do NOT create blank issues
title: "[OTHER] <description>"
labels: ["awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure your issue does not fit in any of the provided templates.
        If so, choose the most appropriate one for your issue.
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
