name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Android NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.1.8937393"

    - name: Configure CMake for ${{ matrix.abi }}
      run: |
        cmake -B build_${{ matrix.abi }} \
          -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk/25.1.8937393/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-24 \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build for ${{ matrix.abi }}
      run: cmake --build build_${{ matrix.abi }} --config Release

    - name: Upload SO for ${{ matrix.abi }}
      uses: actions/upload-artifact@v4
      with:
        name: libmodmenu_${{ matrix.abi }}
        path: build_${{ matrix.abi }}/libmodmenu.so
